import { StyleSheet } from 'react-native';
import { spacing, radius, shadows, typography } from '../../theme';

// ─── Timeline Styles (StopTimelineRow) ───────────────────────────────────────
export const createTimelineStyles = (colors: any) =>
  StyleSheet.create({
    stopTimelineRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      marginBottom: spacing.xs,
    },
    nodeColumn: {
      alignItems: 'center',
      width: 44,
      marginRight: spacing.xs,
    },
    timelineBadge: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: colors.surfaceElevated,
      borderWidth: 2,
      borderColor: colors.borderStrong,
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 2,
      ...shadows.sm,
    },
    timelineBadgeNext: {
      backgroundColor: '#1D4ED8',
      borderColor: '#1D4ED8',
    },
    timelineBadgeCompleted: {
      backgroundColor: colors.success,
      borderColor: colors.success,
    },
    timelineBadgeFailed: {
      backgroundColor: colors.danger,
      borderColor: colors.danger,
    },
    timelineBadgeText: {
      fontSize: 13,
      fontWeight: '800',
      color: colors.textSecondary,
    },
    timelineBadgeTextNext: {
      color: '#FFFFFF',
    },
    timelineVerticalLine: {
      width: 2,
      flex: 1,
      minHeight: 48,
      backgroundColor: colors.border,
      marginTop: -2,
    },
    stopCard: {
      flex: 1,
      backgroundColor: colors.surface,
      borderRadius: radius.md,
      padding: spacing.md,
      borderWidth: 1.5,
      borderColor: colors.border,
      gap: spacing.xs,
      marginBottom: spacing.sm,
      ...shadows.sm,
    },
    stopCardNext: {
      borderColor: '#1D4ED8',
      backgroundColor: colors.surfaceElevated,
      ...shadows.md,
    },
    stopCardPressed: {
      opacity: 0.9,
      transform: [{ scale: 0.99 }],
    },
    stopCardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    timeTagRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    stopTimeText: {
      ...typography.caption,
      color: colors.textMuted,
      fontWeight: '600',
    },
    headerBadgesRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.xs,
    },
    multiPackageBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.primaryGhost,
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: radius.full,
      gap: 3,
    },
    multiPackageText: {
      ...typography.caption,
      fontSize: 10,
      fontWeight: '800',
      color: colors.primary,
    },
    statusPill: {
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: radius.full,
      backgroundColor: colors.surfaceElevated,
      borderWidth: 1,
      borderColor: colors.border,
    },
    statusPillNext: {
      backgroundColor: colors.primaryGhost,
      borderColor: colors.primary,
    },
    statusPillCompleted: {
      backgroundColor: colors.successGhost,
      borderColor: colors.success + '44',
    },
    statusPillFailed: {
      backgroundColor: colors.dangerGhost,
      borderColor: colors.danger + '44',
    },
    statusPillText: {
      ...typography.caption,
      fontSize: 10,
      fontWeight: '700',
      color: colors.textMuted,
    },
    statusPillTextNext: { color: colors.primary },
    statusPillTextCompleted: { color: colors.success },
    statusPillTextFailed: { color: colors.danger },
    stopCardBody: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: spacing.xs,
    },
    addressWrap: {
      flex: 1,
      gap: 2,
    },
    stopAddressText: {
      ...typography.bodyMedium,
      fontWeight: '700',
      color: colors.text,
    },
    stopBairroText: {
      ...typography.caption,
      color: colors.textMuted,
    },
  });

// ─── Screen Styles (MapScreen) ───────────────────────────────────────────────
export const createScreenStyles = (colors: any) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    map: {
      flex: 1,
    },

    // ── User Location Marker ──
    userMarkerRing: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: 'rgba(37, 99, 235, 0.25)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    userMarkerOuter: {
      width: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: '#FFFFFF',
      alignItems: 'center',
      justifyContent: 'center',
      ...shadows.md,
    },
    userMarkerInner: {
      width: 12,
      height: 12,
      borderRadius: 6,
      backgroundColor: colors.primary,
    },

    // ── Multi-Lasso Overlay ──
    lassoOverlay: {
      backgroundColor: 'rgba(15, 23, 42, 0.25)',
      zIndex: 35,
    },
    lassoTopHud: {
      position: 'absolute',
      alignSelf: 'center',
      backgroundColor: 'rgba(15, 23, 42, 0.92)',
      borderRadius: radius.xxl,
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: spacing.lg,
      paddingVertical: spacing.sm,
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.15)',
      gap: spacing.md,
      ...shadows.xl,
    },
    lassoHudCol: {
      alignItems: 'center',
      gap: 2,
    },
    lassoHudLabel: {
      fontSize: 9,
      fontWeight: '800',
      color: '#94A3B8',
      letterSpacing: 0.8,
      textTransform: 'uppercase',
    },
    lassoHudRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    lassoHudVal: {
      fontSize: 13,
      fontWeight: '800',
      color: '#FFFFFF',
    },
    lassoHudDivider: {
      width: 1,
      height: 22,
      backgroundColor: 'rgba(255, 255, 255, 0.15)',
    },
    lassoBottomBar: {
      position: 'absolute',
      bottom: 0,
      left: spacing.md,
      right: spacing.md,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
      zIndex: 40,
    },
    lassoRoundDarkBtn: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: '#0F172A',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.15)',
      ...shadows.md,
    },
    lassoRoundWhiteBtn: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: '#FFFFFF',
      alignItems: 'center',
      justifyContent: 'center',
      ...shadows.md,
    },
    lassoConfirmBtn: {
      flex: 1,
      height: 48,
      borderRadius: 24,
      backgroundColor: '#059669',
      alignItems: 'center',
      justifyContent: 'center',
      ...shadows.lg,
    },
    lassoConfirmBtnText: {
      fontSize: 13,
      fontWeight: '900',
      color: '#FFFFFF',
      letterSpacing: 0.8,
    },
    lassoToggleModeBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      height: 48,
      paddingHorizontal: spacing.md,
      borderRadius: 24,
      gap: 6,
      ...shadows.md,
    },
    lassoToggleModeBtnDraw: {
      backgroundColor: '#7C3AED',
      borderWidth: 1,
      borderColor: '#A78BFA',
    },
    lassoToggleModeBtnPan: {
      backgroundColor: '#2563EB',
      borderWidth: 1,
      borderColor: '#60A5FA',
    },
    lassoToggleModeText: {
      color: '#FFFFFF',
      fontSize: 12,
      fontWeight: '800',
      letterSpacing: 0.5,
    },

    // ── Persistent Floating Action Bar ──
    persistentFloatingBar: {
      position: 'absolute',
      left: spacing.md,
      right: spacing.md,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
      zIndex: 40,
    },
    floatingOptBtn: {
      flex: 1.2,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#1D4ED8',
      paddingVertical: 12,
      paddingHorizontal: spacing.md,
      borderRadius: radius.full,
      gap: 6,
      ...shadows.lg,
    },
    floatingOptBtnActive: {
      backgroundColor: '#6366F1',
    },
    floatingOptBtnText: {
      fontSize: 13,
      fontWeight: '800',
      color: '#FFFFFF',
      letterSpacing: 0.3,
    },
    floatingFinishBtn: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#059669',
      paddingVertical: 12,
      paddingHorizontal: spacing.md,
      borderRadius: radius.full,
      gap: 6,
      ...shadows.lg,
    },
    floatingFinishBtnText: {
      fontSize: 13,
      fontWeight: '800',
      color: '#FFFFFF',
      letterSpacing: 0.3,
    },

    // ── Bottom Sheet ──
    bottomSheet: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: colors.surface,
      borderTopLeftRadius: radius.xxl,
      borderTopRightRadius: radius.xxl,
      borderWidth: 1,
      borderColor: colors.border,
      borderBottomWidth: 0,
      ...shadows.xl,
    },
    dragZone: {
      paddingBottom: spacing.xs,
    },
    handleContainer: {
      alignItems: 'center',
      paddingVertical: spacing.xs + 2,
    },
    handle: {
      width: 46,
      height: 5,
      borderRadius: radius.full,
      backgroundColor: colors.borderStrong,
      alignSelf: 'center',
    },

    // ── Search Bar Row ──
    searchRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.xs,
      gap: spacing.sm,
    },
    iconBtn: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: radius.md,
      backgroundColor: colors.surfaceElevated,
      borderWidth: 1,
      borderColor: colors.border,
    },
    searchInputContainer: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.surfaceElevated,
      borderRadius: radius.lg,
      paddingHorizontal: spacing.md,
      height: 46,
      borderWidth: 1,
      borderColor: colors.border,
      gap: spacing.xs + 2,
    },
    searchInput: {
      flex: 1,
      fontSize: 14,
      color: colors.text,
      fontWeight: '500',
      paddingVertical: 0,
    },
    sheetScroll: {
      flex: 1,
    },
    sheetScrollContent: {
      paddingHorizontal: spacing.md,
      paddingTop: spacing.xs,
      paddingBottom: spacing.xxl + 40,
    },

    // ── Rotas Header ──
    rotasHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: spacing.xs,
      marginTop: 2,
    },
    rotasTitle: {
      ...typography.displayMedium,
      color: colors.text,
    },
    rotasStatusBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.successGhost,
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: radius.full,
      gap: 6,
    },
    rotasStatusDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: colors.success,
    },
    rotasStatusText: {
      ...typography.caption,
      fontWeight: '700',
      color: colors.success,
    },

    // ── Metrics Card ──
    metricsCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.surfaceElevated,
      borderRadius: radius.lg,
      paddingVertical: spacing.md,
      paddingHorizontal: spacing.sm,
      marginVertical: spacing.sm,
      borderWidth: 1,
      borderColor: colors.border,
      ...shadows.sm,
    },
    metricCol: {
      flex: 1,
      alignItems: 'center',
      gap: 2,
    },
    metricVal: {
      ...typography.bodyMedium,
      fontWeight: '800',
      color: colors.text,
      marginTop: 2,
    },
    metricLbl: {
      ...typography.caption,
      color: colors.textMuted,
      fontSize: 11,
    },
    metricDivider: {
      width: 1,
      height: 32,
      backgroundColor: colors.border,
    },

    // ── Origin Row ──
    originSection: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: spacing.xs,
    },
    originDotCol: {
      alignItems: 'center',
      width: 44,
    },
    originDot: {
      width: 14,
      height: 14,
      borderRadius: 7,
      backgroundColor: colors.primary,
      borderWidth: 3,
      borderColor: colors.primaryGhost,
    },
    originLine: {
      width: 2,
      height: 24,
      backgroundColor: colors.border,
    },
    originInfo: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: colors.surfaceElevated,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
      borderRadius: radius.md,
      borderWidth: 1,
      borderColor: colors.border,
      marginLeft: spacing.xs,
    },
    originTextWrap: {
      gap: 1,
    },
    originTitle: {
      ...typography.bodySmall,
      fontWeight: '700',
      color: colors.text,
    },
    originSubtitle: {
      ...typography.caption,
      color: colors.textMuted,
      fontSize: 11,
    },

    // ── Add Stop Row ──
    addStopSection: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: spacing.xs,
    },
    addDot: {
      width: 22,
      height: 22,
      borderRadius: 11,
      backgroundColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },

    // ── Status Subheader ──
    statusSubheader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: spacing.xs + 2,
      marginBottom: spacing.xs,
    },
    optimizedBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.primaryGhost,
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: radius.full,
      gap: 5,
    },
    optimizedText: {
      ...typography.caption,
      fontWeight: '700',
      color: colors.primary,
    },
    stopsCountWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    stopsCountText: {
      ...typography.caption,
      fontWeight: '700',
      color: colors.textSecondary,
    },
    timelineContainer: {
      marginTop: spacing.xs,
    },

    // ── Bottom Actions Bar ──
    bottomBar: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: colors.surface,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
      ...shadows.lg,
    },
    importSheetBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primary,
      borderRadius: radius.md,
      paddingVertical: spacing.md,
      gap: spacing.xs + 2,
    },
    importSheetBtnText: {
      fontSize: 14,
      color: '#FFFFFF',
      fontWeight: '700',
    },
    bottomActionsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
    },
    reoptimizeBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primaryGhost,
      borderRadius: radius.md,
      paddingVertical: spacing.md,
      paddingHorizontal: spacing.lg,
      gap: 6,
      borderWidth: 1,
      borderColor: colors.primary + '33',
    },
    reoptimizeBtnActive: {
      backgroundColor: colors.primary,
      borderColor: colors.primaryDark || colors.primary,
      ...shadows.md,
    },
    reoptimizeBtnText: {
      fontSize: 14,
      color: colors.primary,
      fontWeight: '700',
    },
    reoptimizeBtnTextActive: {
      color: '#FFFFFF',
    },
    finishRouteBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.success,
      borderRadius: radius.md,
      paddingVertical: spacing.md,
      gap: 6,
    },
    finishRouteBtnText: {
      fontSize: 14,
      color: '#FFFFFF',
      fontWeight: '700',
    },
    btnDisabled: {
      opacity: 0.6,
    },
    btnPressed: {
      opacity: 0.85,
      transform: [{ scale: 0.98 }],
    },

    // ── Stop Modal Detail ──
    stopModalOverlay: {
      ...StyleSheet.absoluteFill,
      zIndex: 50,
      justifyContent: 'flex-end',
    },
    modalBackdrop: {
      ...StyleSheet.absoluteFill,
      backgroundColor: 'rgba(15, 23, 42, 0.65)',
    },
    stopModalSheet: {
      backgroundColor: colors.surface,
      borderTopLeftRadius: radius.xxl,
      borderTopRightRadius: radius.xxl,
      paddingHorizontal: spacing.lg,
      paddingTop: spacing.xs,
      gap: spacing.sm,
      maxHeight: '80%',
      ...shadows.xl,
    },
    modalHeaderRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      marginTop: spacing.xs,
    },
    modalStopBadge: {
      ...typography.label,
      color: colors.primary,
      fontWeight: '800',
      letterSpacing: 0.5,
    },
    modalStopName: {
      ...typography.title,
      color: colors.text,
      fontWeight: '800',
      marginTop: 2,
    },
    closeBtn: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: colors.surfaceElevated,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: colors.border,
    },
    modalMetaText: {
      ...typography.caption,
      color: colors.textMuted,
      fontWeight: '600',
    },
    modalDeliveriesList: {
      maxHeight: 180,
      marginVertical: spacing.xs,
    },
    modalDeliveryItem: {
      backgroundColor: colors.surfaceElevated,
      borderRadius: radius.md,
      padding: spacing.sm + 2,
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: spacing.xs,
      gap: 2,
    },
    modalDeliveryHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    modalDeliveryTitle: {
      ...typography.bodySmall,
      fontWeight: '700',
      color: colors.text,
      flex: 1,
    },
    orderPill: {
      backgroundColor: colors.primaryGhost,
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: radius.sm,
    },
    orderPillText: {
      ...typography.caption,
      fontSize: 10,
      fontWeight: '700',
      color: colors.primary,
    },
    modalDeliverySub: {
      ...typography.caption,
      color: colors.textSecondary,
    },
    modalDeliveryNotes: {
      ...typography.caption,
      color: colors.textMuted,
      fontStyle: 'italic',
    },
    modalActionsRow: {
      flexDirection: 'row',
      gap: spacing.sm,
      marginVertical: spacing.xs,
    },
    modalActionBtn: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.surfaceElevated,
      borderRadius: radius.md,
      paddingVertical: spacing.sm + 2,
      borderWidth: 1,
      borderColor: colors.border,
      gap: 6,
    },
    modalActionBtnText: {
      ...typography.caption,
      fontWeight: '700',
      color: colors.text,
    },
    modalStatusRow: {
      flexDirection: 'row',
      gap: spacing.sm,
      marginTop: spacing.xs,
    },
    modalStatusBtn: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: radius.md,
      paddingVertical: spacing.md,
      gap: 6,
      ...shadows.sm,
    },
    modalStatusBtnText: {
      fontSize: 14,
      color: '#FFFFFF',
      fontWeight: '700',
    },

    // ── Loop Badges ──
    loopBadgeContainer: {
      position: 'absolute',
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 100,
    },
    loopBadgeCircle: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: '#6366F1',
      borderWidth: 2.5,
      borderColor: '#FFFFFF',
      alignItems: 'center',
      justifyContent: 'center',
      ...shadows.md,
      elevation: 8,
    },
    loopBadgeText: {
      color: '#FFFFFF',
      fontSize: 14,
      fontWeight: '900',
    },

    // ── Loading Modal Overlay ──
    loadingModalOverlay: {
      ...StyleSheet.absoluteFill,
      backgroundColor: 'rgba(10, 15, 30, 0.75)',
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 9999,
      paddingHorizontal: spacing.lg,
    },
    loadingModalCard: {
      width: '100%',
      maxWidth: 320,
      backgroundColor: colors.surface,
      borderRadius: radius.xl,
      borderWidth: 1,
      borderColor: colors.border,
      paddingVertical: spacing.xl,
      paddingHorizontal: spacing.lg,
      alignItems: 'center',
      justifyContent: 'center',
      gap: spacing.sm,
      ...shadows.xl,
      elevation: 12,
    },
    loadingModalTitle: {
      ...typography.title,
      color: colors.text,
      fontWeight: '800',
      fontSize: 17,
      textAlign: 'center',
      marginTop: spacing.xs,
    },
    loadingModalSub: {
      ...typography.caption,
      color: colors.textSecondary,
      textAlign: 'center',
      lineHeight: 18,
    },
  });
